spring:
  application:
    name: skoda-demo
  mvc:
    servlet:
      path: /api/v1
  jackson:
    default-property-inclusion: non-null
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  jakarta:
    persistence:
      jdbc:
        url: org.postgresql.Driver
  datasource:
    password: Test123!
    url: jdbc:postgresql://127.0.0.1:5432/skoda_demo?createDatabaseIfNotExist=true
    username: skoda-demo
    driver-class-name: org.postgresql.Driver
