spring:
  datasource:
    password: 87654321
    url: jdbc:postgresql://awseb-e-7hq739aia3-stack-awsebrdsdatabase-ckyv28x74rvu.ctqag8iqkfhc.eu-north-1.rds.amazonaws.com:5432/skoda_demo?createDatabaseIfNotExist=true
    username: sa
